name: foodie
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^3.1.0
  google_fonts: ^6.1.0
  flutter_slidable: ^3.1.0
  multi_dropdown: ^2.1.4
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  provider: ^6.1.2
  dio: ^5.4.2+1
  http: ^1.2.1
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/

